#  Compose file version 3 reference: https://docs.docker.com/compose/compose-file/
version: "3.5"

services:
  mongodb:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js # init mongodb from init-mongo.js
      - ./runtime/mongo_data:/data/db
    privileged: true

  rabbitmq:
    image: rabbitmq:3.13.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./runtime/rabbitmq_data:/var/lib/rabbitmq
    privileged: true

  redis:
    image: redis:7.0
    volumes:
      - ./runtime/redis_data:/data
    privileged: true

  flower:
    image: msp/python:latest
    command: [ "sh", "-c", "cd /vagrant && make flower-up" ]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - MONGODB_HOST=mongodb
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - BROWER_USER=${BROWER_USER}
      - BROWER_PASSWORD=${BROWER_PASSWORD}
    # remove the port mapping in prod env, because we use nginx to proxy the request
    ports:
      - "8081:8081"
    volumes:
      - ./:/vagrant
    depends_on:
      - rabbitmq
      - mongodb
    privileged: true

  uvicorn:
    image: msp/uvicorn:latest
    working_dir: /app
    volumes:
      - ./web/:/app
    # remove the port mapping in prod env, because we use nginx to proxy the request
    ports:
      - "8080:80"
    environment:
      - APP_MODULE=main:app
      - TIMEOUT=1200
      - GRACEFUL_TIMEOUT=1200
      - OPENAPI_PREFIX=
      - MONGODB_HOST=mongodb
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - FLOWER_API_BASE_URL=http://flower:8081
      - BROWER_USER=${BROWER_USER}
      - BROWER_PASSWORD=${BROWER_PASSWORD}
    depends_on:
      - flower
      - mongodb
    privileged: true

  nginx:
    image: nginx:1.27.1
    ports:
      - "80:80"
    volumes:
      - ./docker/images/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/images/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/images/nginx/etc/nginx/ssl/:/etc/nginx/ssl
      - ./runtime/logs/nginx:/var/log/nginx
    depends_on:
      - flower
      - uvicorn
    privileged: true
